noun = input("type in a noun")
adjective = input("Type in a adjective")
item = input("Type in a item")
Verb = input("Type in a verb")
emote = input ("Type in a emote")
food = input("type in  a food")
car = input("type in a car")
name = input("type in a name")
game = input("type in a game")
movies = input("type in a movie")


print("Kids should get paid for %s because they would want to have %s " % (emote, food))
print("The first reason is that kids would try or already have %s and would be proud for getting %s " % (noun, item))
print("They would also want to do more with %s. While they are in school they are getting %s" % (game, movies))
print("While they are getting good %s. They will use it on %s " % (car, Verb))
print("After they use %s they will be happy with %s" % (noun, item))
